/******************************************************************************/
/*                                                                            */
/* Program: Sticky2.exe                                                       */
/*                                                                            */
/* Description: TCP Sticky Pad                                                */
/*                                                                            */
/* File Name : ABOUT.H                                                        */
/*                                                                            */
/* Author : ANDREW J. WYSOCKI                                                 */
/*                                                                            */
/* Copyright 1996 Copyright AB Software                                       */
/*                                                                            */
/* Generated using VisPro/C serial number VPC5020318                          */
/*                                                                            */
/******************************************************************************/

#ifndef ABOUTWINDOW_H
#define ABOUTWINDOW_H

 /* ##START Form.39 Form header definitions */
 /* ##END Form header definitions */
HWND OpenABOUT(HWND hwndOwner, PVOID pInfo);

#define ID_FORMTIMER 100   /* Used for timer events */
#endif